---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-app
data:
  hello_msg: friend
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: simple-app-node
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31111
  selector:
    app: simple-app
    channel: dev-unstable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
      channel: dev-unstable
  template:
    metadata:
      labels:
        app: simple-app
        channel: dev-unstable
    spec:
      containers:
      - name: simple-app
        image: docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        env:
        - name: HELLO_MSG
          valueFrom:
            configMapKeyRef:
              name: simple-app
              key: hello_msg
