---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-node
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: echo-port
    nodePort: 30000
  selector:
    app: simple-app
    channel: dev-unstable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
      channel: dev-unstable
  template:
    metadata:
      labels:
        app: simple-app
        channel: dev-unstable
    spec:
      containers:
      - name: simple-app
        image: hashicorp/http-echo:1.0.0
        args:
          - -text
          - this is a demo
        ports:
          - containerPort: 5678
            name: echo-port
