#@ load("@ytt:data", "data")

#@ def labels():
app: application-simple
channel: #@ data.values.channel
#@ end


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-app
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/versioned: ""
data:
  TEXT: Hello Kubecon friends!
---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ data.values.namespace
  name: simple-app
spec:
  ports:
  - port: 80
    targetPort: echo-port
    name: echo-port
  selector: #@ labels()

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ data.values.namespace
  name: simple-app
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: simple-app
        image: hashicorp/http-echo:1.0.0
        args:
          - -text
          - $(TEXT)
        ports:
        - containerPort: 5678
          name: echo-port
        envFrom:
        - configMapRef:
            name: simple-app

#@ for/end domain in data.values.domains:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #@ "simple-app-{}".format(domain)
  namespace: #@ data.values.namespace
spec:
  rules:
  - host: #@ "{}.127.0.0.1.nip.io".format(domain)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app
            port:
              name: echo-port

#@ if/end data.values.namespace:
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
