#@ load("@ytt:data","data")

#@ def labels():
app: simple-app
channel: dev-unstable
#@ end

#@ if data.values.namespace != "" and data.values.namespace != "default":
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ data.values.namespace
  name: simple-app-node
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31111
  selector: #@ labels()
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ data.values.namespace
  name: simple-app
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: simple-app
        image: docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        env:
        - name: HELLO_MSG
          valueFrom:
            configMapKeyRef:
              name: simple-app
              key: hello_msg
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: #@ data.values.namespace
  name: simple-app
data:
  hello_msg: #@ data.values.message