#@ load("@ytt:overlay", "overlay")

#@ cm = overlay.subset({"kind": "ConfigMap"})
#@overlay/match by=cm, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/versioned: ""
