apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: carvel.garnier.wf
  namespace: installs
spec:
  displayName: Carvel Demo
  longDescription: A cool app to showcase Carvel at Kubecon EU 2024
  shortDescription: Kubecon Carvel Demo
